# 
# Export functions:
#	build_test_project(project_name)
#

MACRO(build_test_project NAME)
	set_complie_flags(${EXE_COMPILE_FLAGS})

	FILE(GLOB_RECURSE SOURCES ${ROOT_DIR}/test/${NAME}/*)

	IF(WIN32)
		SET(LINK_LIBS "ws2_32.lib;${OUTPUT_TARGET_LIB}.lib")
		IF(GNUTLS_LIBRARY)
			SET(LINK_LIBS "${LINK_LIBS};${GNUTLS_LIBRARY}")
		ENDIF()
	ELSEIF(UNIX)
		SET(LINK_LIBS "pthread ${OUTPUT_TARGET_LIB}")
        IF(GNUTLS_LIBRARY)
            SET(LINK_LIBS "${LINK_LIBS} ${GNUTLS_LIBRARY}")
        ENDIF()
	ENDIF()
	
	ADD_EXECUTABLE(${NAME} ${SOURCES})
	TARGET_LINK_LIBRARIES (${NAME} ${LINK_LIBS})
	
	IF(WIN32)
		SET_TARGET_PROPERTIES(${NAME} PROPERTIES VS_DEBUGGER_ENVIRONMENT "PATH=${ROOT_DIR}/lib;%PATH%")
	ENDIF()
ENDMACRO()
