#
# Config build environment
#

# Specifies library name
SET(SHARED_LIBRARY_NAME "pump")
SET(STATIC_LIBRARY_NAME "pump_static")

# Specifies build type
IF(BUILD_DEBUG)
	SET(CMAKE_BUILD_TYPE Debug)
	SET(pump_WITH_DEBUG_LOG "WITH_DEBUG_LOG")
ELSE()
	SET(CMAKE_BUILD_TYPE Release)
	SET(pump_WITH_DEBUG_LOG "WITHOUT_DEBUG_LOG")
	# The macro disable assert
	ADD_DEFINITIONS("-DNDEBUG")
ENDIF()
SET(CMAKE_CONFIGURATION_TYPES ${CMAKE_BUILD_TYPE} CACHE STRING "" FORCE)

# Specifies suffix of libraries for finding and linking
IF(WIN32)
	SET(CMAKE_FIND_LIBRARY_SUFFIXES "${CMAKE_FIND_LIBRARY_SUFFIXES};.a")
ENDIF()

# Specifies project prefix path
SET(CMAKE_PREFIX_PATH ${ROOT_DIR}/lib)

# Specifies libraries path
LINK_DIRECTORIES(${ROOT_DIR}/lib)
LINK_DIRECTORIES(${CMAKE_BINARY_DIR})

# Specifies include path
INCLUDE_DIRECTORIES(${ROOT_DIR}/src)
INCLUDE_DIRECTORIES(${ROOT_DIR}/include)
MESSAGE(STATUS "INCLUDE path: ${ROOT_DIR}")

# Specifies unicode character set on windows
IF(WIN32)
	REMOVE_DEFINITIONS("-D_MBCS")
	ADD_DEFINITIONS("-DUNICODE")
	ADD_DEFINITIONS("-D_UNICODE")
	ADD_DEFINITIONS("-DWIN32_LEAN_AND_MEAN")
ENDIF()