#
# Export variables:
#   JEMALLOC_LIBRARY - jemalloc library link path
#

IF(WITH_JEMALLOC)
	IF(BUILD_DEBUG)
		FIND_LIBRARY(JEMALLOC_LIBRARY NAMES jemallocd libjemallocd)
	ELSE()
		FIND_LIBRARY(JEMALLOC_LIBRARY NAMES jemalloc libjemalloc)
	ENDIF()
	
	SET(pump_WITH_JEMALLOC "WITH_JEMALLOC")
	MESSAGE(STATUS "Jemalloc library: ${JEMALLOC_LIBRARY}")
ELSE()
	SET(pump_WITH_JEMALLOC "WITHOUT_JEMALLOC")
ENDIF()
