#
# Define macros: 
#   WITH_GNUTLS WITH_OPENSSL 
#
# Export variables:
#	TLS_LIBRARY - gnutls library link path
#	CRYPTO_LIBRARY - crypto library link path
#

IF(WITH_TLS)
	FIND_LIBRARY(OPENSSL_LIBRARY NAMES ssl libssl)
	IF(NOT OPENSSL_LIBRARY STREQUAL "OPENSSL_LIBRARY-NOTFOUND")
		FIND_LIBRARY(CRYPTO_LIBRARY NAMES crypto libcrypto)
	ELSE()
		FIND_LIBRARY(GNUTLS_LIBRARY NAMES gnutls libgnutls libgnutls.dll)
	ENDIF()
	
	IF(NOT OPENSSL_LIBRARY STREQUAL "OPENSSL_LIBRARY-NOTFOUND")
		SET(TLS_LIBRARY "${OPENSSL_LIBRARY}")
		SET(pump_WITH_TLS "WITH_OPENSSL")
		MESSAGE(STATUS "TLS library: ${OPENSSL_LIBRARY}")
	ELSEIF(NOT GNUTLS_LIBRARY STREQUAL "GNUTLS_LIBRARY-NOTFOUND")
		SET(TLS_LIBRARY "${GNUTLS_LIBRARY}")
		SET(pump_WITH_TLS "WITH_GNUTLS")
		MESSAGE(STATUS "TLS library: ${GNUTLS_LIBRARY}")
	ELSE()
		SET(pump_WITH_TLS "WITHOUT_TLS")
		MESSAGE(STATUS "TLS library: not found")
	ENDIF()
ELSE()
	SET(pump_WITH_TLS "WITHOUT_TLS")
ENDIF()